# fly.toml file generated for junpi on 2021-11-16T20:59:58+09:00

app = "junpi"


[experimental]
  private_network = true

[mount]
  destination = "/data"
  source = "nginx_data"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 100
    soft_limit = 30
    type = "requests"

  [[services.http_checks]]
    interval = 3000
    method = "get"
    path = "/healthz"
    protocol = "http"
    restart_limit = 0
    timeout = 1000

    [services.http_checks.headers]
      Host = "health.check"

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

  [[services.script_checks]]
    command = "/fly/check-nodes.sh"
    interval = 10000
    restart_limit = 0
    timeout = 1000
